name: Python CI/CD Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: windows-latest  # Запуск на Windows (можна змінити на ubuntu-latest за потреби)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Завантажує репозиторій у середовище

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Вказати потрібну версію Python, яка підтримується проектом

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest    

      - name: Run software tests
        run: |
          python -m coverage run -m pytest --junitxml=test-reports/results.xml soft_tests.py
          python -m coverage report soft_tests.py
          python -m coverage html -d coverage_html_report_soft_tests

      - name: Upload test results
        if: always()  # Цей крок виконується навіть при провалі тестів
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/results.xml  # Завантажує результати тестів у артефакти

      - name: Upload coverage report
        if: always()  # Цей крок виконується навіть при провалі тестів
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage_html_report_soft_tests  # Завантажує звіт про покриття у артефакти
